# Site settings
title: David Shute
email: hey.ugly@davidshute.ca
description: Writer, musician, media dabbler, language enthusiast, homebrewer, software tester, man with too many hobbies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidshute.ca" # the base hostname & protocol for your site
twitter_username: davidshute
github_username:  dshute

# Build settings
markdown: kramdown
